### ISSUE TITLE
@octokit/rest is deprecated

### ISSUE THREAD

**Issue by slavafomin** [mheap/pin-github-action#25]
Hello!

Thank you for this great tool!

However, I'm getting the following deprecation notices when using it:

```bash
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated.
Use `const { Octokit } = require("@octokit/rest")` instead

Deprecation: [@octokit/request-error] `error.headers` is deprecated, use `error.response.headers`.
    at RequestError.get (~/.nvm/versions/node/v14.17.0/lib/node_modules/pin-github-action/node_modules/@octokit/request/node_modules/@octokit/request-error/dist-node/index.js:64:24)
    at authenticationRequestError (~/.nvm/versions/node/v14.17.0/lib/node_modules/pin-github-action/node_modules/@octokit/rest/plugins/authentication-deprecated/request-error.js:7:14)
    at ~/.nvm/versions/node/v14.17.0/lib/node_modules/pin-github-action/node_modules/before-after-hook/lib/add.js:37:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ~/.nvm/versions/node/v14.17.0/lib/node_modules/pin-github-action/findRefOnGithub.js:17:11
```

**Comment by mheap** [comment]
I've just released v1.3.1 with all dependencies upgraded to the latest version. Thanks for the report! ❤️
